// Generated by LiveScript 1.5.0
(function(){
  var Adapter;
  Adapter = (function(){
    Adapter.displayName = 'Adapter';
    var prototype = Adapter.prototype, constructor = Adapter;
    Adapter.create = function(config){
      switch (config.db.type) {
      case 'mysql' || 'postgres':
        return new (require('./SQL'))(config.db);
      }
    };
    Adapter.prototype.query = function(){
      throw Error('unimplemented');
    };
    function Adapter(){}
    return Adapter;
  }());
  module.exports = Adapter;
}).call(this);
