// Generated by LiveScript 1.5.0
(function(){
  var Adapter;
  Adapter = (function(){
    Adapter.displayName = 'Adapter';
    var prototype = Adapter.prototype, constructor = Adapter;
    function Adapter(config){
      this.client = config.type;
      this.database = config.database;
      this.host = config.host;
      this.connection = config;
    }
    Adapter.create = function(config){
      switch (config.db.type) {
      case 'mysql' || 'postgres':
        return new (require('./SQL'))(config.db);
      case 'mongodb':
        return new (require('./MongoDB'))(config.db);
      }
    };
    Adapter.prototype.query = function(){
      throw Error('unimplemented');
    };
    Adapter.prototype.select = function(){
      throw Error('unimplemented');
    };
    Adapter.prototype.where = function(){
      throw Error('unimplemented');
    };
    return Adapter;
  }());
  module.exports = Adapter;
}).call(this);
