// Generated by LiveScript 1.5.0
(function(){
  var Adapter;
  Adapter = (function(){
    Adapter.displayName = 'Adapter';
    var prototype = Adapter.prototype, constructor = Adapter;
    function Adapter(){}
    return Adapter;
  }());
  module.exports = Adapter;
}).call(this);
