// Generated by LiveScript 1.5.0
(function(){
  var QueryBuilder, Model;
  QueryBuilder = require('./QueryBuilder');
  Model = (function(){
    Model.displayName = 'Model';
    var prototype = Model.prototype, constructor = Model;
    function Model(name, adapter){
      this.name = name;
      this.adapter = adapter;
    }
    Model.prototype.fetch = function(){
      return new QueryBuilder(this);
    };
    return Model;
  }());
  module.exports = Model;
}).call(this);
