// Generated by LiveScript 1.5.0
(function(){
  var Promise, Adapter, each, QueryBuilder, _createMiddleware;
  Promise = require('bluebird');
  Adapter = require('./adapters/Adapter');
  each = require('prelude-ls').each;
  QueryBuilder = (function(){
    QueryBuilder.displayName = 'QueryBuilder';
    var prototype = QueryBuilder.prototype, constructor = QueryBuilder;
    QueryBuilder.prototype.queries = [];
    function QueryBuilder(model){
      this.model = model;
    }
    QueryBuilder.prototype.then = function(done){
      return this.model.adapter.query(this);
    };
    return QueryBuilder;
  }());
  _createMiddleware = function(name){
    return QueryBuilder.prototype[name] = function(it){
      this.queries.push({
        method: name,
        params: it
      });
      return this;
    };
  };
  each(_createMiddleware)(
  ['select', 'where', 'limit']);
  module.exports = QueryBuilder;
}).call(this);
