// Generated by LiveScript 1.5.0
(function(){
  var Promise, Adapter, QueryBuilder;
  Promise = require('bluebird');
  Adapter = require('./adapters/Adapter');
  QueryBuilder = (function(){
    QueryBuilder.displayName = 'QueryBuilder';
    var prototype = QueryBuilder.prototype, constructor = QueryBuilder;
    function QueryBuilder(model){
      this.model = model;
    }
    QueryBuilder.prototype.then = function(cb){
      return this.model.adapter.query(this).then(cb);
    };
    return QueryBuilder;
  }());
  module.exports = QueryBuilder;
}).call(this);
