// Generated by LiveScript 1.5.0
(function(){
  var MongoClient, test, url, Thor, User;
  MongoClient = require('mongodb').MongoClient;
  test = require('assert');
  url = 'mongodb://localhost:27017/test';
  MongoClient.connect(url, function(err, db){
    var adminDb;
    adminDb = db.admin();
    return adminDb.listDatabases(function(err, dbs){
      test.equal(null, err);
      test.ok(dbs.databases.length > 0);
      return db.close();
    });
  });
  Thor = require('.');
  Thor.config({
    db: {
      type: 'mysql',
      host: '127.0.0.1',
      user: 'root',
      password: 'root',
      database: 'test'
    }
  });
  User = Thor.Model('user');
  User.fetch().then(console.log)['catch'](console.error);
}).call(this);
