// Generated by LiveScript 1.5.0
(function(){
  var Thor, User;
  Thor = require('.');
  Thor.config({
    db: {
      type: 'mongodb',
      host: 'mongodb://127.0.0.1:27017',
      user: 'root',
      password: 'root',
      database: 'test'
    }
  });
  User = Thor.Model('user');
  User.fetch().then();
}).call(this);
